import type { Product, Brand, PromoCode } from "./types";

// Use a placeholder image service that always works, plus local images as backup
const img = (path: string) => path;

export const BRANDS: Brand[] = [
  {
    id: "maison-noir",
    name: "Maison Noir",
    description: "Bold Parisian fragrances for the modern iconoclast.",
    country: "France",
    founded: 1923,
  },
  {
    id: "aurelia",
    name: "Aurelia",
    description: "Italian craftsmanship meets timeless floral elegance.",
    country: "Italy",
    founded: 1947,
  },
  {
    id: "kintsugi",
    name: "Kintsugi",
    description: "Japanese-inspired niche perfumery, where broken things become beautiful.",
    country: "Japan",
    founded: 2014,
  },
  {
    id: "atelier-oud",
    name: "Atelier Oud",
    description: "Pure Arabian oud, distilled from heritage in Abu Dhabi.",
    country: "UAE",
    founded: 1998,
  },
  {
    id: "london-fog",
    name: "London Fog",
    description: "Crisp, woody, distinctly British.",
    country: "United Kingdom",
    founded: 1891,
  },
  {
    id: "verdant",
    name: "Verdant",
    description: "Clean, green, modern. Born in California.",
    country: "USA",
    founded: 2009,
  },
  {
    id: "rosa-velvet",
    name: "Rosa Velvet",
    description: "Bulgarian rose fields meet French perfumery.",
    country: "Bulgaria",
    founded: 1962,
  },
  {
    id: "noir-cedar",
    name: "Noir Cedar",
    description: "Smoky, resinous, unapologetically masculine.",
    country: "USA",
    founded: 1978,
  },
];

export const PRODUCTS: Product[] = [
  // MEN
  {
    id: "mn-001",
    slug: "nocturne-noir-eau-de-parfum",
    name: "Nocturne Noir",
    brand: "Maison Noir",
    category: "men",
    gender: "men",
    concentration: "EDP",
    scentFamily: ["oriental", "woody", "spicy"],
    description:
      "A brooding evening scent built around black amber, smoked oud, and bitter cocoa. Wears close to the skin, then announces itself after the first hour.",
    brandStory:
      "Born in a Parisian atelier in 1923, Maison Noir built its reputation on compositions that refuse to be polite. Nocturne Noir is the house's signature — a love letter to the city after midnight.",
    topNotes: ["Bergamot", "Black Pepper", "Cardamom"],
    heartNotes: ["Iris", "Bulgarian Rose", "Smoked Tea"],
    baseNotes: ["Black Amber", "Oud", "Bitter Cocoa", "Vetiver"],
    longevity: "Long-lasting",
    sillage: "Strong",
    variants: [
      { size: "30ml", price: 95, stock: 12 },
      { size: "50ml", price: 145, stock: 24 },
      { size: "100ml", price: 215, stock: 8 },
    ],
    images: [
      img("/products/0.jpg"),
      img("/products/4.jpg"),
      img("/products/8.jpg"),
    ],
    rating: 4.8,
    reviewCount: 412,
    reviews: [
      {
        id: "r1",
        user: "Marcus J.",
        avatar: "M",
        rating: 5,
        date: "2026-06-12",
        title: "My signature scent",
        body: "I get compliments every time I wear this. Lasts 8+ hours on my skin and the drydown is incredible. Smells like a high-end gentleman's club.",
        verified: true,
        helpful: 87,
        unhelpful: 4,
      },
      {
        id: "r2",
        user: "Ahmed K.",
        avatar: "A",
        rating: 5,
        date: "2026-05-30",
        title: "Sophisticated and unique",
        body: "Not your typical designer scent. The oud is present but not overpowering. Perfect for evening events and cold weather.",
        photos: ["/products/9.jpg"],
        verified: true,
        helpful: 56,
        unhelpful: 2,
      },
      {
        id: "r3",
        user: "Elena R.",
        avatar: "E",
        rating: 4,
        date: "2026-04-18",
        title: "Bought for my husband",
        body: "He loves it. A bit heavy for summer but absolutely perfect for fall/winter evenings.",
        verified: true,
        helpful: 23,
        unhelpful: 1,
      },
    ],
    qa: [
      {
        id: "q1",
        user: "Sam T.",
        question: "How does this compare to Tom Ford Oud Wood?",
        answer: "Nocturne Noir is significantly smokier and more resinous, with a real oud note vs. the synthetic oud in Oud Wood. They're both excellent but serve different moods.",
        answeredBy: "Perfumeria Concierge",
        date: "2026-07-02",
      },
      {
        id: "q2",
        user: "Priya N.",
        question: "Is this suitable for daytime office wear?",
        answer: "It's a little intense for a tight office environment. We recommend 1-2 sprays max, applied to chest rather than neck.",
        answeredBy: "Perfumeria Concierge",
        date: "2026-06-28",
      },
    ],
    isBestseller: true,
    isFeatured: true,
  },
  {
    id: "mn-002",
    slug: "cedar-smoke",
    name: "Cedar Smoke",
    brand: "Noir Cedar",
    category: "men",
    gender: "men",
    concentration: "EDT",
    scentFamily: ["woody", "leather", "smoky"],
    description:
      "Smoldering Atlas cedar, charred birch, and a whisper of leather. The cabin-in-the-woods fantasy, bottled.",
    brandStory:
      "Noir Cedar has been sourcing the finest cedarwood from Atlas Mountains since 1978. Cedar Smoke is our most loved release — a love letter to the great outdoors.",
    topNotes: ["Pink Pepper", "Juniper", "Lemon Zest"],
    heartNotes: ["Atlas Cedar", "Cypress", "Geranium"],
    baseNotes: ["Charred Birch", "Leather", "Sandalwood", "Tonka"],
    longevity: "Long-lasting",
    sillage: "Moderate",
    variants: [
      { size: "50ml", price: 88, stock: 18 },
      { size: "100ml", price: 135, stock: 15 },
    ],
    images: [img("/products/1.jpg"), img("/products/5.jpg")],
    rating: 4.6,
    reviewCount: 287,
    reviews: [
      {
        id: "r4",
        user: "Derek L.",
        avatar: "D",
        rating: 5,
        date: "2026-07-05",
        title: "Smells like a campfire in the best way",
        body: "This is woody done right. Not synthetic, not sharp. Just pure cedar and smoke. Got my second bottle already.",
        verified: true,
        helpful: 41,
        unhelpful: 0,
      },
    ],
    qa: [],
    isNew: true,
  },
  {
    id: "mn-003",
    slug: "london-fog-original",
    name: "Original Eau de Cologne",
    brand: "London Fog",
    category: "men",
    gender: "men",
    concentration: "EDC",
    scentFamily: ["citrus", "fresh", "aromatic"],
    description:
      "A classic British cologne, bright and bracing. Lavender, citrus, and a clean mossy drydown.",
    brandStory:
      "Since 1891, London Fog has dressed British gentlemen with sharp, clean fragrances. The Original is unchanged for over a century.",
    topNotes: ["Bergamot", "Lemon", "Lavender"],
    heartNotes: ["Rosemary", "Nutmeg", "Petitgrain"],
    baseNotes: ["Oakmoss", "Sandalwood", "White Musk"],
    longevity: "Moderate",
    sillage: "Intimate",
    variants: [
      { size: "100ml", price: 75, stock: 32 },
      { size: "200ml", price: 130, stock: 10 },
    ],
    images: [img("/products/2.jpg"), img("/products/6.jpg")],
    rating: 4.5,
    reviewCount: 523,
    reviews: [
      {
        id: "r5",
        user: "James W.",
        avatar: "J",
        rating: 5,
        date: "2026-06-01",
        title: "A timeless classic",
        body: "My grandfather wore this. My father wore this. Now I do. Smells like a clean, polished gentleman.",
        verified: true,
        helpful: 78,
        unhelpful: 1,
      },
    ],
    qa: [],
    isBestseller: true,
  },

  // WOMEN
  {
    id: "wo-001",
    slug: "rosa-velvet-eau-de-parfum",
    name: "Rosa Velvet",
    brand: "Rosa Velvet",
    category: "women",
    gender: "women",
    concentration: "EDP",
    scentFamily: ["floral", "oriental"],
    description:
      "A modern rose. Bulgarian rose absolute layered with peony, lychee, and a base of warm cashmere woods.",
    brandStory:
      "Rosa Velvet partners directly with rose farmers in the Valley of the Roses in Bulgaria, distilling our own absolutes since 1962.",
    topNotes: ["Lychee", "Pear", "Pink Pepper"],
    heartNotes: ["Bulgarian Rose", "Peony", "Magnolia"],
    baseNotes: ["Cashmere Wood", "White Musk", "Vanilla"],
    longevity: "Long-lasting",
    sillage: "Moderate",
    variants: [
      { size: "30ml", price: 110, stock: 8 },
      { size: "50ml", price: 165, stock: 16 },
      { size: "100ml", price: 240, stock: 6 },
    ],
    images: [img("/products/3.jpg"), img("/products/7.jpg")],
    rating: 4.9,
    reviewCount: 891,
    reviews: [
      {
        id: "r6",
        user: "Sophie M.",
        avatar: "S",
        rating: 5,
        date: "2026-07-10",
        title: "My wedding scent",
        body: "I wore this on my wedding day and I get stopped every time I wear it. It's become my signature. The drydown is divine.",
        photos: ["/products/4.jpg"],
        verified: true,
        helpful: 134,
        unhelpful: 2,
      },
      {
        id: "r7",
        user: "Camille D.",
        avatar: "C",
        rating: 5,
        date: "2026-06-22",
        title: "Not your grandma's rose",
        body: "Modern, romantic, and lasts all day. I smell like a bouquet that lasts. Worth every penny.",
        verified: true,
        helpful: 92,
        unhelpful: 0,
      },
    ],
    qa: [
      {
        id: "q3",
        user: "Hannah L.",
        question: "Is this a heavy fragrance?",
        answer: "No, it's surprisingly fresh and modern. The rose is balanced with bright top notes, so it never feels old-fashioned.",
        answeredBy: "Perfumeria Concierge",
        date: "2026-07-01",
      },
    ],
    isBestseller: true,
    isFeatured: true,
  },
  {
    id: "wo-002",
    slug: "aurelia-fiori-bianchi",
    name: "Fiori Bianchi",
    brand: "Aurelia",
    category: "women",
    gender: "women",
    concentration: "EDP",
    scentFamily: ["floral", "green", "fresh"],
    description:
      "White flowers after the rain. Tuberose, jasmine sambac, and a clean fig-leaf base.",
    brandStory:
      "Hand-blended in a small atelier outside Florence, Aurelia crafts each bottle in small batches using locally-sourced botanicals.",
    topNotes: ["Italian Bergamot", "Green Mandarin", "Pear Nectar"],
    heartNotes: ["Tuberose", "Jasmine Sambac", "Orange Blossom"],
    baseNotes: ["Fig Leaf", "White Cedar", "Skin Musk"],
    longevity: "Moderate",
    sillage: "Intimate",
    variants: [
      { size: "50ml", price: 125, stock: 14 },
      { size: "100ml", price: 195, stock: 9 },
    ],
    images: [img("/products/4.jpg"), img("/products/8.jpg")],
    rating: 4.7,
    reviewCount: 342,
    reviews: [
      {
        id: "r8",
        user: "Isabella R.",
        avatar: "I",
        rating: 5,
        date: "2026-06-15",
        title: "A summer garden in a bottle",
        body: "So fresh and clean. I wear it every day in spring and summer. Compliments everywhere.",
        verified: true,
        helpful: 67,
        unhelpful: 1,
      },
    ],
    qa: [],
    isNew: true,
  },
  {
    id: "wo-003",
    slug: "aurelia-velvet-rose",
    name: "Velvet Rose Oud",
    brand: "Aurelia",
    category: "women",
    gender: "women",
    concentration: "Parfum",
    scentFamily: ["floral", "oriental", "woody"],
    description:
      "A high-concentration velvet rose draped in oud, saffron, and a dusting of cocoa. For the romantic maximalist.",
    brandStory: "An Aurelia heritage release, reformulated in 2024 with a richer, more intense heart.",
    topNotes: ["Saffron", "Pink Pepper", "Bulgarian Rose"],
    heartNotes: ["Damask Rose", "Turkish Rose", "Patchouli"],
    baseNotes: ["Oud", "Cocoa", "Sandalwood", "Amber"],
    longevity: "All-day",
    sillage: "Strong",
    variants: [
      { size: "30ml", price: 175, stock: 6 },
      { size: "50ml", price: 245, stock: 11 },
    ],
    images: [img("/products/5.jpg"), img("/products/9.jpg")],
    rating: 4.8,
    reviewCount: 198,
    reviews: [
      {
        id: "r9",
        user: "Layla A.",
        avatar: "L",
        rating: 5,
        date: "2026-05-20",
        title: "Heady and addictive",
        body: "One spray is enough. It's heavy, sensual, and lasts 12+ hours. My favorite winter scent.",
        verified: true,
        helpful: 45,
        unhelpful: 0,
      },
    ],
    qa: [],
  },

  // UNISEX
  {
    id: "un-001",
    slug: "kintsugi-ceremony",
    name: "Ceremony",
    brand: "Kintsugi",
    category: "unisex",
    gender: "unisex",
    concentration: "EDP",
    scentFamily: ["woody", "green", "smoky"],
    description:
      "A meditative blend of hinoki wood, matcha, and white tea smoke. Wabi-sabi in a bottle.",
    brandStory:
      "Kintsugi is a small-batch Japanese perfumery that finds beauty in imperfection. Each fragrance is hand-numbered.",
    topNotes: ["Yuzu", "Matcha", "Bergamot"],
    heartNotes: ["Hinoki Wood", "Bamboo", "White Tea"],
    baseNotes: ["Vetiver", "Hinoki Smoke", "Soft Musk"],
    longevity: "Moderate",
    sillage: "Moderate",
    variants: [
      { size: "50ml", price: 165, stock: 12 },
      { size: "100ml", price: 235, stock: 5 },
    ],
    images: [img("/products/6.jpg"), img("/products/0.jpg")],
    rating: 4.9,
    reviewCount: 267,
    reviews: [
      {
        id: "r10",
        user: "Maya T.",
        avatar: "M",
        rating: 5,
        date: "2026-07-08",
        title: "Calming and unique",
        body: "Smells like a Japanese tea ceremony. Subtle, sophisticated, and so different from anything else in my collection.",
        photos: ["/products/2.jpg"],
        verified: true,
        helpful: 78,
        unhelpful: 0,
      },
    ],
    qa: [],
    isFeatured: true,
    isNew: true,
  },
  {
    id: "un-002",
    slug: "verdant-citrus-no-7",
    name: "Citrus No. 7",
    brand: "Verdant",
    category: "unisex",
    gender: "unisex",
    concentration: "EDT",
    scentFamily: ["citrus", "fresh", "green"],
    description:
      "A bright, juicy blend of seven citrus fruits with a clean vetiver base. California sunshine in a spray.",
    brandStory:
      "Verdant is a clean beauty house from California. Citrus No. 7 is their breakout hit, made with cold-pressed essential oils.",
    topNotes: ["Sicilian Lemon", "Pink Grapefruit", "Mandarin", "Yuzu", "Bergamot", "Lime", "Kumquat"],
    heartNotes: ["Neroli", "Petitgrain", "Green Tea"],
    baseNotes: ["Vetiver", "Cedarwood", "White Musk"],
    longevity: "Light",
    sillage: "Intimate",
    variants: [
      { size: "30ml", price: 58, stock: 22 },
      { size: "50ml", price: 88, stock: 30 },
      { size: "100ml", price: 145, stock: 18 },
    ],
    images: [img("/products/7.jpg"), img("/products/1.jpg")],
    rating: 4.6,
    reviewCount: 612,
    reviews: [
      {
        id: "r11",
        user: "Theo K.",
        avatar: "T",
        rating: 5,
        date: "2026-06-29",
        title: "The perfect summer scent",
        body: "Light, fresh, and crowd-pleasing. Doesn't last forever but that's fine — reapply and enjoy.",
        verified: true,
        helpful: 89,
        unhelpful: 3,
      },
    ],
    qa: [],
    isBestseller: true,
  },
  {
    id: "un-003",
    slug: "kintsugi-iron-tea",
    name: "Iron Tea",
    brand: "Kintsugi",
    category: "unisex",
    gender: "unisex",
    concentration: "Parfum",
    scentFamily: ["woody", "leather", "smoky"],
    description:
      "A smoky, tannic blend of lapsang souchong tea, black iron, and worn leather. The most-bookish scent we make.",
    brandStory: "Limited edition, hand-bottled in numbered runs of 500.",
    topNotes: ["Black Pepper", "Smoked Plum"],
    heartNotes: ["Lapsang Souchong", "Tobacco Leaf", "Birch Tar"],
    baseNotes: ["Leather", "Iron", "Oud", "Vetiver"],
    longevity: "All-day",
    sillage: "Strong",
    variants: [
      { size: "30ml", price: 215, stock: 4 },
      { size: "50ml", price: 295, stock: 7 },
    ],
    images: [img("/products/8.jpg"), img("/products/2.jpg")],
    rating: 4.9,
    reviewCount: 87,
    reviews: [
      {
        id: "r12",
        user: "Rashid B.",
        avatar: "R",
        rating: 5,
        date: "2026-04-12",
        title: "Worth every dollar",
        body: "A true collector's piece. Smells like an old library, a smoking jacket, and a leather chair. Stunning.",
        verified: true,
        helpful: 34,
        unhelpful: 0,
      },
    ],
    qa: [],
  },

  // NICHE
  {
    id: "ni-001",
    slug: "kintsugi-paper-lantern",
    name: "Paper Lantern",
    brand: "Kintsugi",
    category: "niche",
    gender: "unisex",
    concentration: "Parfum",
    scentFamily: ["floral", "green", "woody"],
    description:
      "A whisper of wisteria, rice paper, and fresh ink. The scent of a paper lantern glowing at dusk.",
    brandStory:
      "An award-winning niche release, Paper Lantern won the 2025 Art & Olfaction Award in the independent category.",
    topNotes: ["Wisteria", "Rice Steam", "White Tea"],
    heartNotes: ["Magnolia", "Iris", "Bamboo"],
    baseNotes: ["Hinoki Wood", "Soft Musk", "Vellum"],
    longevity: "Moderate",
    sillage: "Intimate",
    variants: [
      { size: "30ml", price: 245, stock: 3 },
      { size: "50ml", price: 345, stock: 5 },
    ],
    images: [img("/products/9.jpg"), img("/products/3.jpg")],
    rating: 5.0,
    reviewCount: 64,
    reviews: [
      {
        id: "r13",
        user: "Anna K.",
        avatar: "A",
        rating: 5,
        date: "2026-07-12",
        title: "Pure artistry",
        body: "An olfactory poem. Subtle, fleeting, and haunting. I save it for special evenings.",
        verified: true,
        helpful: 41,
        unhelpful: 0,
      },
    ],
    qa: [],
    isFeatured: true,
  },
  {
    id: "ni-002",
    slug: "maison-noir-cuir-sacre",
    name: "Cuir Sacré",
    brand: "Maison Noir",
    category: "niche",
    gender: "unisex",
    concentration: "Parfum",
    scentFamily: ["leather", "woody", "smoky"],
    description:
      "Sacred leather, frankincense smoke, and aged birch tar. A cathedral of a fragrance.",
    brandStory: "A 2024 release, Cuir Sacré was composed over three years by our master perfumer in Grasse.",
    topNotes: ["Saffron", "Cardamom", "Black Pepper"],
    heartNotes: ["Frankincense", "Myrrh", "Cistus"],
    baseNotes: ["Sacre Leather", "Birch Tar", "Oud", "Vetiver"],
    longevity: "All-day",
    sillage: "Enormous",
    variants: [
      { size: "30ml", price: 285, stock: 4 },
      { size: "50ml", price: 395, stock: 6 },
    ],
    images: [img("/products/0.jpg"), img("/products/5.jpg")],
    rating: 4.9,
    reviewCount: 142,
    reviews: [
      {
        id: "r14",
        user: "Viktor P.",
        avatar: "V",
        rating: 5,
        date: "2026-05-08",
        title: "Masterpiece",
        body: "Powerful, dark, and absolutely unique. I get stopped on the street. Lasts 14+ hours.",
        verified: true,
        helpful: 52,
        unhelpful: 0,
      },
    ],
    qa: [],
    isNew: true,
  },

  // ARABIC / OUD
  {
    id: "ar-001",
    slug: "atelier-oud-royal",
    name: "Royal Oud",
    brand: "Atelier Oud",
    category: "arabic",
    gender: "unisex",
    concentration: "Parfum",
    scentFamily: ["oriental", "woody", "spicy"],
    description:
      "Pure Cambodian oud, aged 25 years, layered with royal saffron, rose, and amber. A modern classic of Arabian perfumery.",
    brandStory:
      "Atelier Oud has been distilling oud in Abu Dhabi since 1998, working with the finest agarwood from Cambodia, India, and Laos.",
    topNotes: ["Saffron", "Pink Pepper", "Green Cardamom"],
    heartNotes: ["Cambodian Oud", "Taif Rose", "Saffron Absolute"],
    baseNotes: ["Royal Amber", "Sandalwood", "White Musk", "Dehn Al Oud"],
    longevity: "All-day",
    sillage: "Enormous",
    variants: [
      { size: "12ml", price: 195, stock: 8 },
      { size: "30ml", price: 395, stock: 5 },
      { size: "50ml", price: 595, stock: 3 },
    ],
    images: [img("/categories/0.jpg"), img("/categories/2.jpg")],
    rating: 4.9,
    reviewCount: 387,
    reviews: [
      {
        id: "r15",
        user: "Faisal M.",
        avatar: "F",
        rating: 5,
        date: "2026-06-25",
        title: "The real deal",
        body: "Authentic Cambodian oud. Not the synthetic stuff you find elsewhere. Worth every riyal.",
        verified: true,
        helpful: 91,
        unhelpful: 0,
      },
      {
        id: "r16",
        user: "Noura A.",
        avatar: "N",
        rating: 5,
        date: "2026-05-17",
        title: "My special-occasion scent",
        body: "I save it for Eid and weddings. The compliments never stop. Truly exceptional.",
        verified: true,
        helpful: 64,
        unhelpful: 1,
      },
    ],
    qa: [
      {
        id: "q4",
        user: "Khalid R.",
        question: "Is this pure oud or blended?",
        answer: "Royal Oud is a high-concentration parfum with genuine Cambodian oud at the heart, blended with supporting notes. It is not pure distillation (which would be much more expensive and niche).",
        answeredBy: "Perfumeria Concierge",
        date: "2026-06-20",
      },
    ],
    isBestseller: true,
    isFeatured: true,
  },
  {
    id: "ar-002",
    slug: "atelier-oud-mukhallat",
    name: "Mukhallat Maliki",
    brand: "Atelier Oud",
    category: "arabic",
    gender: "unisex",
    concentration: "Parfum",
    scentFamily: ["oriental", "floral", "spicy"],
    description:
      "A traditional mukhallat blend of oud, rose, amber, and musk. Worn in the Gulf for generations.",
    brandStory:
      "Our master perfumer's grandfather made this exact blend in his shop in Deira in 1962. We reformulated it in 2018.",
    topNotes: ["Saffron", "Cinnamon", "Green Cardamom"],
    heartNotes: ["Oud", "Taif Rose", "Jasmine"],
    baseNotes: ["Amber", "Musk", "Sandalwood", "Dehn"],
    longevity: "All-day",
    sillage: "Strong",
    variants: [
      { size: "30ml", price: 145, stock: 12 },
      { size: "50ml", price: 225, stock: 8 },
    ],
    images: [img("/categories/1.jpg"), img("/categories/3.jpg")],
    rating: 4.8,
    reviewCount: 256,
    reviews: [
      {
        id: "r17",
        user: "Yasmin H.",
        avatar: "Y",
        rating: 5,
        date: "2026-04-30",
        title: "Traditional and authentic",
        body: "Takes me back to my grandmother's house. A true classic.",
        verified: true,
        helpful: 38,
        unhelpful: 0,
      },
    ],
    qa: [],
  },
  {
    id: "ar-003",
    slug: "atelier-oud-amber-dawn",
    name: "Amber Dawn",
    brand: "Atelier Oud",
    category: "arabic",
    gender: "unisex",
    concentration: "EDP",
    scentFamily: ["oriental", "spicy", "gourmand"],
    description:
      "Warm amber, vanilla, and a whisper of frankincense. The first golden hour after sunrise.",
    brandStory: "A modern interpretation of traditional amber compositions, launched in 2023.",
    topNotes: ["Pink Pepper", "Bergamot"],
    heartNotes: ["Amber", "Frankincense", "Cinnamon Bark"],
    baseNotes: ["Vanilla", "Benzoin", "Sandalwood", "White Musk"],
    longevity: "Long-lasting",
    sillage: "Moderate",
    variants: [
      { size: "50ml", price: 115, stock: 18 },
      { size: "100ml", price: 185, stock: 11 },
    ],
    images: [img("/categories/2.jpg"), img("/categories/4.jpg")],
    rating: 4.7,
    reviewCount: 178,
    reviews: [
      {
        id: "r18",
        user: "Omar B.",
        avatar: "O",
        rating: 5,
        date: "2026-05-22",
        title: "Warm and comforting",
        body: "Like a hug in a bottle. Perfect for cold weather.",
        verified: true,
        helpful: 29,
        unhelpful: 0,
      },
    ],
    qa: [],
    isNew: true,
  },

  // GIFT SETS
  {
    id: "gs-001",
    slug: "discovery-set-classic",
    name: "Classic Discovery Set",
    brand: "Maison Noir",
    category: "gift-sets",
    gender: "unisex",
    concentration: "EDP",
    scentFamily: ["floral", "woody", "oriental"],
    description:
      "A curated set of five 10ml travel sprays from our most-loved releases. The perfect way to find your new signature.",
    brandStory: "The Discovery Set is our most popular gift, designed for sampling or for the traveler who won't compromise.",
    topNotes: ["Mixed"],
    heartNotes: ["Mixed"],
    baseNotes: ["Mixed"],
    longevity: "Moderate",
    sillage: "Moderate",
    variants: [{ size: "5 x 10ml", price: 95, stock: 30 }],
    images: [img("/categories/3.jpg"), img("/categories/5.jpg")],
    rating: 4.8,
    reviewCount: 1243,
    reviews: [
      {
        id: "r19",
        user: "Olivia P.",
        avatar: "O",
        rating: 5,
        date: "2026-07-01",
        title: "Best way to find your signature",
        body: "Tried all five and ended up buying two full bottles. The travel size is perfect for my purse.",
        photos: ["/categories/3.jpg"],
        verified: true,
        helpful: 156,
        unhelpful: 3,
      },
    ],
    qa: [],
    isBestseller: true,
    isFeatured: true,
  },
  {
    id: "gs-002",
    slug: "his-and-hers-gift-set",
    name: "His & Hers Discovery",
    brand: "Aurelia",
    category: "gift-sets",
    gender: "unisex",
    concentration: "EDP",
    scentFamily: ["floral", "woody"],
    description:
      "Two of our most-loved fragrances in a beautifully boxed gift set. Includes Rosa Velvet (her) and Cedar Smoke (him).",
    brandStory: "Our bestselling gift for couples, available seasonally in limited-edition packaging.",
    topNotes: ["Mixed"],
    heartNotes: ["Mixed"],
    baseNotes: ["Mixed"],
    longevity: "Long-lasting",
    sillage: "Moderate",
    variants: [{ size: "2 x 50ml", price: 245, stock: 18 }],
    images: [img("/categories/4.jpg"), img("/categories/6.jpg")],
    rating: 4.9,
    reviewCount: 412,
    reviews: [
      {
        id: "r20",
        user: "James & Sarah",
        avatar: "J",
        rating: 5,
        date: "2026-02-14",
        title: "Anniversary perfection",
        body: "Bought this for our anniversary and we both love it. The packaging is gorgeous too.",
        verified: true,
        helpful: 87,
        unhelpful: 0,
      },
    ],
    qa: [],
    isFeatured: true,
  },
  {
    id: "gs-003",
    slug: "luxury-oud-collection",
    name: "Luxury Oud Collection",
    brand: "Atelier Oud",
    category: "gift-sets",
    gender: "unisex",
    concentration: "Parfum",
    scentFamily: ["oriental", "woody", "spicy"],
    description:
      "Our most prestigious oud collection: Royal Oud, Mukhallat Maliki, and Amber Dawn in a hand-finished wooden box.",
    brandStory:
      "The Luxury Oud Collection is presented in a hand-finished walnut box, with a numbered certificate of authenticity.",
    topNotes: ["Mixed"],
    heartNotes: ["Mixed"],
    baseNotes: ["Mixed"],
    longevity: "All-day",
    sillage: "Strong",
    variants: [{ size: "3 x 30ml", price: 695, stock: 6 }],
    images: [img("/categories/5.jpg"), img("/categories/7.jpg")],
    rating: 5.0,
    reviewCount: 78,
    reviews: [
      {
        id: "r21",
        user: "Sheikh Mohammed A.",
        avatar: "S",
        rating: 5,
        date: "2026-03-22",
        title: "An heirloom",
        body: "Bought for my father. The presentation is stunning. The fragrances are even better.",
        verified: true,
        helpful: 24,
        unhelpful: 0,
      },
    ],
    qa: [],
    isNew: true,
  },

  // More men
  {
    id: "mn-004",
    slug: "maison-noir-vetiver-noir",
    name: "Vetiver Noir",
    brand: "Maison Noir",
    category: "men",
    gender: "men",
    concentration: "EDT",
    scentFamily: ["woody", "earthy", "aromatic"],
    description:
      "Haitian vetiver, smoked black tea, and a touch of grapefruit. Sharp, modern, magnetic.",
    brandStory: "Our bestselling everyday men's scent since 2019.",
    topNotes: ["Grapefruit", "Black Pepper", "Cardamom"],
    heartNotes: ["Smoked Tea", "Geranium", "Sage"],
    baseNotes: ["Haitian Vetiver", "Cedarwood", "Tonka Bean"],
    longevity: "Moderate",
    sillage: "Moderate",
    variants: [
      { size: "50ml", price: 95, stock: 25 },
      { size: "100ml", price: 145, stock: 18 },
    ],
    images: [img("/products/1.jpg"), img("/products/5.jpg")],
    rating: 4.6,
    reviewCount: 678,
    reviews: [
      {
        id: "r22",
        user: "Tom H.",
        avatar: "T",
        rating: 5,
        date: "2026-06-08",
        title: "Daily driver",
        body: "My go-to for the office. Clean, masculine, never overpowering.",
        verified: true,
        helpful: 56,
        unhelpful: 0,
      },
    ],
    qa: [],
    isBestseller: true,
  },
  {
    id: "mn-005",
    slug: "verdant-ocean-mist",
    name: "Ocean Mist",
    brand: "Verdant",
    category: "men",
    gender: "men",
    concentration: "EDT",
    scentFamily: ["aquatic", "fresh", "citrus"],
    description:
      "Sea salt, driftwood, and white musk. A clean, breezy aquatic.",
    brandStory: "A summer 2024 release inspired by the California coast.",
    topNotes: ["Sea Salt", "Bergamot", "Cucumber"],
    heartNotes: ["Driftwood", "Sage", "Mint"],
    baseNotes: ["White Musk", "Ambergris", "Cedar"],
    longevity: "Light",
    sillage: "Moderate",
    variants: [
      { size: "50ml", price: 75, stock: 22 },
      { size: "100ml", price: 115, stock: 14 },
    ],
    images: [img("/products/2.jpg"), img("/products/6.jpg")],
    rating: 4.4,
    reviewCount: 312,
    reviews: [
      {
        id: "r23",
        user: "Chris M.",
        avatar: "C",
        rating: 4,
        date: "2026-05-14",
        title: "Fresh and clean",
        body: "Great for summer. Doesn't last as long as I'd like but it smells great while it's there.",
        verified: true,
        helpful: 22,
        unhelpful: 1,
      },
    ],
    qa: [],
  },
  // More women
  {
    id: "wo-004",
    slug: "rosa-velvet-noir-rose",
    name: "Noir Rose",
    brand: "Rosa Velvet",
    category: "women",
    gender: "women",
    concentration: "EDP",
    scentFamily: ["floral", "gourmand", "oriental"],
    description:
      "A dark, modern rose. Damask rose, black cherry, and a base of patchouli and vanilla.",
    brandStory: "The dark sister to our original Rosa Velvet, launched in 2023.",
    topNotes: ["Black Cherry", "Bergamot", "Pink Pepper"],
    heartNotes: ["Damask Rose", "Liqueur", "Geranium"],
    baseNotes: ["Patchouli", "Vanilla", "Sandalwood"],
    longevity: "Long-lasting",
    sillage: "Strong",
    variants: [
      { size: "30ml", price: 125, stock: 9 },
      { size: "50ml", price: 185, stock: 13 },
    ],
    images: [img("/products/3.jpg"), img("/products/7.jpg")],
    rating: 4.8,
    reviewCount: 421,
    reviews: [
      {
        id: "r24",
        user: "Beatriz S.",
        avatar: "B",
        rating: 5,
        date: "2026-04-25",
        title: "A modern rose masterpiece",
        body: "Reminds me of Tom Ford's Lost Cherry but better. Long-lasting, unique, gorgeous.",
        verified: true,
        helpful: 73,
        unhelpful: 1,
      },
    ],
    qa: [],
  },
  {
    id: "wo-005",
    slug: "aurelia-vanilla-velvet",
    name: "Vanilla Velvet",
    brand: "Aurelia",
    category: "women",
    gender: "women",
    concentration: "EDP",
    scentFamily: ["gourmand", "oriental", "floral"],
    description:
      "Madagascar vanilla, tonka bean, and a heart of jasmine. Warm, sweet, comforting.",
    brandStory: "Our bestselling gourmand release of 2024.",
    topNotes: ["Bergamot", "Mandarin"],
    heartNotes: ["Jasmine", "Heliotrope", "Almond"],
    baseNotes: ["Madagascar Vanilla", "Tonka Bean", "Sandalwood", "White Musk"],
    longevity: "Long-lasting",
    sillage: "Moderate",
    variants: [
      { size: "50ml", price: 115, stock: 20 },
      { size: "100ml", price: 175, stock: 12 },
    ],
    images: [img("/products/4.jpg"), img("/products/8.jpg")],
    rating: 4.7,
    reviewCount: 567,
    reviews: [
      {
        id: "r25",
        user: "Emma J.",
        avatar: "E",
        rating: 5,
        date: "2026-06-30",
        title: "Cozy and addictive",
        body: "Smells like vanilla cake, in the best possible way. I want to bathe in it.",
        verified: true,
        helpful: 91,
        unhelpful: 2,
      },
    ],
    qa: [],
    isBestseller: true,
  },
  {
    id: "un-004",
    slug: "verdant-fig-leaf",
    name: "Fig Leaf & Tea",
    brand: "Verdant",
    category: "unisex",
    gender: "unisex",
    concentration: "EDT",
    scentFamily: ["green", "fresh", "woody"],
    description:
      "Fresh fig leaf, green tea, and a clean cedarwood base. The most 'California' scent we make.",
    brandStory: "A summer staple, launched in 2022.",
    topNotes: ["Fig Leaf", "Lemon", "Green Tea"],
    heartNotes: ["Fig", "Jasmine", "Mint"],
    baseNotes: ["Cedarwood", "White Musk", "Sandalwood"],
    longevity: "Light",
    sillage: "Intimate",
    variants: [
      { size: "50ml", price: 85, stock: 18 },
      { size: "100ml", price: 135, stock: 9 },
    ],
    images: [img("/products/5.jpg"), img("/products/9.jpg")],
    rating: 4.5,
    reviewCount: 289,
    reviews: [
      {
        id: "r26",
        user: "Sara L.",
        avatar: "S",
        rating: 5,
        date: "2026-07-04",
        title: "A green dream",
        body: "So fresh and clean. I wear it in summer and get compliments daily.",
        verified: true,
        helpful: 41,
        unhelpful: 0,
      },
    ],
    qa: [],
  },
];

export const PROMO_CODES: PromoCode[] = [
  {
    code: "WELCOME10",
    type: "percent",
    value: 10,
    minOrder: 50,
    description: "10% off your first order over $50",
    expiresAt: "2026-12-31",
  },
  {
    code: "SCENT20",
    type: "percent",
    value: 20,
    minOrder: 150,
    description: "20% off orders over $150",
    expiresAt: "2026-12-31",
  },
  {
    code: "GIFT15",
    type: "fixed",
    value: 15,
    minOrder: 75,
    description: "$15 off gift sets over $75",
    expiresAt: "2026-12-31",
  },
  {
    code: "OUD25",
    type: "percent",
    value: 25,
    minOrder: 200,
    description: "25% off oud collection over $200",
    expiresAt: "2026-12-31",
  },
];

export const FAQS = [
  {
    category: "Authenticity",
    items: [
      {
        q: "Are your perfumes authentic?",
        a: "Yes. Every fragrance we sell is sourced directly from the brand or their authorized distributors. We provide a certificate of authenticity with every order and a 100% money-back authenticity guarantee.",
      },
      {
        q: "Do you sell tester or unboxed items?",
        a: "All items are brand new in original manufacturer packaging unless explicitly marked as 'decanted' or 'tester' in the product description. We never sell used fragrances.",
      },
    ],
  },
  {
    category: "Shipping",
    items: [
      {
        q: "How long does shipping take?",
        a: "Standard shipping within the US takes 3-5 business days. Express options are available at checkout. International orders typically arrive within 7-14 business days.",
      },
      {
        q: "Do you ship internationally?",
        a: "Yes — we ship to 75+ countries. International shipping rates and delivery times are calculated at checkout based on your address.",
      },
      {
        q: "Is shipping free?",
        a: "We offer free standard shipping on US orders over $75. International orders over $150 qualify for free standard shipping.",
      },
    ],
  },
  {
    category: "Returns & Exchanges",
    items: [
      {
        q: "What is your return policy?",
        a: "Unopened items in original packaging can be returned within 30 days for a full refund. For hygiene reasons, opened fragrances are non-returnable unless damaged or defective.",
      },
      {
        q: "What if my order arrives damaged?",
        a: "Contact us within 48 hours of delivery with a photo of the damage. We'll send a free replacement immediately, no return required.",
      },
    ],
  },
  {
    category: "Account & Orders",
    items: [
      {
        q: "Do I need an account to order?",
        a: "No — we offer guest checkout. Creating a free account lets you track orders, save addresses, build a wishlist, and earn rewards.",
      },
      {
        q: "How do I track my order?",
        a: "Once your order ships, you'll receive a tracking link via email. You can also view all order status updates in your account dashboard.",
      },
    ],
  },
  {
    category: "Scent Advice",
    items: [
      {
        q: "How do I pick the right fragrance?",
        a: "Take our 'Find Your Scent' quiz for personalized recommendations, or browse by scent family. Our Discovery Sets are the best way to sample multiple fragrances before committing.",
      },
      {
        q: "What's the difference between EDT, EDP, and Parfum?",
        a: "These are concentration levels. EDT (Eau de Toilette) is 5-15% perfume oil — light and refreshing. EDP (Eau de Parfum) is 15-20% — more concentrated and longer-lasting. Parfum is 20-30% — the richest and most long-lasting.",
      },
    ],
  },
];

export const SCENT_FAMILIES: { id: string; label: string; description: string; emoji: string }[] = [
  { id: "floral", label: "Floral", description: "Rose, jasmine, peony, lily of the valley", emoji: "🌸" },
  { id: "woody", label: "Woody", description: "Cedar, sandalwood, vetiver, oud", emoji: "🌳" },
  { id: "citrus", label: "Citrus", description: "Bergamot, lemon, grapefruit, mandarin", emoji: "🍋" },
  { id: "oriental", label: "Oriental", description: "Amber, vanilla, spices, resins", emoji: "✨" },
  { id: "fresh", label: "Fresh", description: "Aquatic, green, aromatic, herbal", emoji: "💨" },
  { id: "gourmand", label: "Gourmand", description: "Vanilla, chocolate, coffee, caramel", emoji: "🍰" },
  { id: "aquatic", label: "Aquatic", description: "Sea salt, marine, ocean breeze", emoji: "🌊" },
  { id: "green", label: "Green", description: "Fig leaf, grass, leaves, herbs", emoji: "🌿" },
  { id: "spicy", label: "Spicy", description: "Pepper, saffron, cinnamon, cardamom", emoji: "🌶️" },
  { id: "leather", label: "Leather", description: "Suede, smoke, tobacco, birch", emoji: "🧥" },
];

export const CATEGORIES = [
  { id: "women", label: "Women", icon: "♀", description: "Elegant florals, sweet gourmands, and modern musks" },
  { id: "men", label: "Men", icon: "♂", description: "Woods, spices, and aromatic compositions" },
  { id: "unisex", label: "Unisex", icon: "⚥", description: "For everyone, regardless of convention" },
  { id: "niche", label: "Niche", icon: "✦", description: "Artisan and avant-garde perfumery" },
  { id: "arabic", label: "Arabic / Oud", icon: "۞", description: "Traditional oud, amber, and mukhallat" },
  { id: "gift-sets", label: "Gift Sets", icon: "🎁", description: "Curated sets for every occasion" },
];

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter((p) => p.category === category);
}

export function getProductsByIds(ids: string[]): Product[] {
  return ids.map((id) => getProductById(id)).filter(Boolean) as Product[];
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  // Products with overlapping scent families or same brand, excluding self
  return PRODUCTS.filter((p) => p.id !== product.id)
    .map((p) => {
      let score = 0;
      if (p.brand === product.brand) score += 3;
      const sharedFamilies = p.scentFamily.filter((f) => product.scentFamily.includes(f)).length;
      score += sharedFamilies * 2;
      if (p.category === product.category) score += 1;
      return { product: p, score };
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map((x) => x.product);
}

export function getMinMaxPrice(): { min: number; max: number } {
  const prices = PRODUCTS.flatMap((p) => p.variants.map((v) => v.price));
  return { min: Math.min(...prices), max: Math.max(...prices) };
}
