-- 08_seed.sql
-- Generated from perfumeria/lib/data.ts — 8 brands + 24 products + reviews/QA/variants + 4 promo codes.
-- Run AFTER 01..07 are applied. Idempotent: truncates catalog tables first.

begin;

-- Wipe catalog tables (keeps profiles, orders, etc.)
truncate table public.product_qa        cascade;
truncate table public.product_reviews   cascade;
truncate table public.product_variants  cascade;
truncate table public.products          cascade;
truncate table public.brands            cascade;
truncate table public.promo_codes       cascade;

-- ===== Brands =====
insert into public.brands (slug, name, description, country, founded) values ('maison-noir', 'Maison Noir', 'Bold Parisian fragrances for the modern iconoclast.', 'France', 1923);
insert into public.brands (slug, name, description, country, founded) values ('aurelia', 'Aurelia', 'Italian craftsmanship meets timeless floral elegance.', 'Italy', 1947);
insert into public.brands (slug, name, description, country, founded) values ('kintsugi', 'Kintsugi', 'Japanese-inspired niche perfumery, where broken things become beautiful.', 'Japan', 2014);
insert into public.brands (slug, name, description, country, founded) values ('atelier-oud', 'Atelier Oud', 'Pure Arabian oud, distilled from heritage in Abu Dhabi.', 'UAE', 1998);
insert into public.brands (slug, name, description, country, founded) values ('london-fog', 'London Fog', 'Crisp, woody, distinctly British.', 'United Kingdom', 1891);
insert into public.brands (slug, name, description, country, founded) values ('verdant', 'Verdant', 'Clean, green, modern. Born in California.', 'USA', 2009);
insert into public.brands (slug, name, description, country, founded) values ('rosa-velvet', 'Rosa Velvet', 'Bulgarian rose fields meet French perfumery.', 'Bulgaria', 1962);
insert into public.brands (slug, name, description, country, founded) values ('noir-cedar', 'Noir Cedar', 'Smoky, resinous, unapologetically masculine.', 'USA', 1978);

-- ===== Products =====
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('nocturne-noir-eau-de-parfum', 'Nocturne Noir', (select id from public.brands where name = 'Maison Noir' limit 1), 'men'::product_category, 'men'::gender_t, 'EDP'::concentration, ARRAY['oriental','woody','spicy'], 'A brooding evening scent built around black amber, smoked oud, and bitter cocoa. Wears close to the skin, then announces itself after the first hour.', 'Born in a Parisian atelier in 1923, Maison Noir built its reputation on compositions that refuse to be polite. Nocturne Noir is the house''s signature — a love letter to the city after midnight.', ARRAY['Bergamot','Black Pepper','Cardamom'], ARRAY['Iris','Bulgarian Rose','Smoked Tea'], ARRAY['Black Amber','Oud','Bitter Cocoa','Vetiver'], 'Long-lasting'::longevity_t, 'Strong'::sillage_t, 4.8, 412, false, true, true, false, NULL, '{}', ARRAY['/products/0.jpg','/products/4.jpg','/products/8.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'nocturne-noir-eau-de-parfum' limit 1), '30ml', 95, 12);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'nocturne-noir-eau-de-parfum' limit 1), '50ml', 145, 24);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'nocturne-noir-eau-de-parfum' limit 1), '100ml', 215, 8);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'nocturne-noir-eau-de-parfum' limit 1), 'Marcus J.', 'M', 5, '2026-06-12'::date, 'My signature scent', 'I get compliments every time I wear this. Lasts 8+ hours on my skin and the drydown is incredible. Smells like a high-end gentleman''s club.', '{}', true, 87, 4);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'nocturne-noir-eau-de-parfum' limit 1), 'Ahmed K.', 'A', 5, '2026-05-30'::date, 'Sophisticated and unique', 'Not your typical designer scent. The oud is present but not overpowering. Perfect for evening events and cold weather.', ARRAY['/products/9.jpg'], true, 56, 2);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'nocturne-noir-eau-de-parfum' limit 1), 'Elena R.', 'E', 4, '2026-04-18'::date, 'Bought for my husband', 'He loves it. A bit heavy for summer but absolutely perfect for fall/winter evenings.', '{}', true, 23, 1);
insert into public.product_qa (product_id, user_name, question, answer, answered_by, qa_date) values ((select id from public.products where slug = 'nocturne-noir-eau-de-parfum' limit 1), 'Sam T.', 'How does this compare to Tom Ford Oud Wood?', 'Nocturne Noir is significantly smokier and more resinous, with a real oud note vs. the synthetic oud in Oud Wood. They''re both excellent but serve different moods.', 'Perfumeria Concierge', '2026-07-02'::date);
insert into public.product_qa (product_id, user_name, question, answer, answered_by, qa_date) values ((select id from public.products where slug = 'nocturne-noir-eau-de-parfum' limit 1), 'Priya N.', 'Is this suitable for daytime office wear?', 'It''s a little intense for a tight office environment. We recommend 1-2 sprays max, applied to chest rather than neck.', 'Perfumeria Concierge', '2026-06-28'::date);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('cedar-smoke', 'Cedar Smoke', (select id from public.brands where name = 'Noir Cedar' limit 1), 'men'::product_category, 'men'::gender_t, 'EDT'::concentration, ARRAY['woody','leather','smoky'], 'Smoldering Atlas cedar, charred birch, and a whisper of leather. The cabin-in-the-woods fantasy, bottled.', 'Noir Cedar has been sourcing the finest cedarwood from Atlas Mountains since 1978. Cedar Smoke is our most loved release — a love letter to the great outdoors.', ARRAY['Pink Pepper','Juniper','Lemon Zest'], ARRAY['Atlas Cedar','Cypress','Geranium'], ARRAY['Charred Birch','Leather','Sandalwood','Tonka'], 'Long-lasting'::longevity_t, 'Moderate'::sillage_t, 4.6, 287, true, false, false, false, NULL, '{}', ARRAY['/products/1.jpg','/products/5.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'cedar-smoke' limit 1), '50ml', 88, 18);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'cedar-smoke' limit 1), '100ml', 135, 15);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'cedar-smoke' limit 1), 'Derek L.', 'D', 5, '2026-07-05'::date, 'Smells like a campfire in the best way', 'This is woody done right. Not synthetic, not sharp. Just pure cedar and smoke. Got my second bottle already.', '{}', true, 41, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('london-fog-original', 'Original Eau de Cologne', (select id from public.brands where name = 'London Fog' limit 1), 'men'::product_category, 'men'::gender_t, 'EDC'::concentration, ARRAY['citrus','fresh','aromatic'], 'A classic British cologne, bright and bracing. Lavender, citrus, and a clean mossy drydown.', 'Since 1891, London Fog has dressed British gentlemen with sharp, clean fragrances. The Original is unchanged for over a century.', ARRAY['Bergamot','Lemon','Lavender'], ARRAY['Rosemary','Nutmeg','Petitgrain'], ARRAY['Oakmoss','Sandalwood','White Musk'], 'Moderate'::longevity_t, 'Intimate'::sillage_t, 4.5, 523, false, true, false, false, NULL, '{}', ARRAY['/products/2.jpg','/products/6.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'london-fog-original' limit 1), '100ml', 75, 32);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'london-fog-original' limit 1), '200ml', 130, 10);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'london-fog-original' limit 1), 'James W.', 'J', 5, '2026-06-01'::date, 'A timeless classic', 'My grandfather wore this. My father wore this. Now I do. Smells like a clean, polished gentleman.', '{}', true, 78, 1);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('rosa-velvet-eau-de-parfum', 'Rosa Velvet', (select id from public.brands where name = 'Rosa Velvet' limit 1), 'women'::product_category, 'women'::gender_t, 'EDP'::concentration, ARRAY['floral','oriental'], 'A modern rose. Bulgarian rose absolute layered with peony, lychee, and a base of warm cashmere woods.', 'Rosa Velvet partners directly with rose farmers in the Valley of the Roses in Bulgaria, distilling our own absolutes since 1962.', ARRAY['Lychee','Pear','Pink Pepper'], ARRAY['Bulgarian Rose','Peony','Magnolia'], ARRAY['Cashmere Wood','White Musk','Vanilla'], 'Long-lasting'::longevity_t, 'Moderate'::sillage_t, 4.9, 891, false, true, true, false, NULL, '{}', ARRAY['/products/3.jpg','/products/7.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'rosa-velvet-eau-de-parfum' limit 1), '30ml', 110, 8);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'rosa-velvet-eau-de-parfum' limit 1), '50ml', 165, 16);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'rosa-velvet-eau-de-parfum' limit 1), '100ml', 240, 6);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'rosa-velvet-eau-de-parfum' limit 1), 'Sophie M.', 'S', 5, '2026-07-10'::date, 'My wedding scent', 'I wore this on my wedding day and I get stopped every time I wear it. It''s become my signature. The drydown is divine.', ARRAY['/products/4.jpg'], true, 134, 2);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'rosa-velvet-eau-de-parfum' limit 1), 'Camille D.', 'C', 5, '2026-06-22'::date, 'Not your grandma''s rose', 'Modern, romantic, and lasts all day. I smell like a bouquet that lasts. Worth every penny.', '{}', true, 92, 0);
insert into public.product_qa (product_id, user_name, question, answer, answered_by, qa_date) values ((select id from public.products where slug = 'rosa-velvet-eau-de-parfum' limit 1), 'Hannah L.', 'Is this a heavy fragrance?', 'No, it''s surprisingly fresh and modern. The rose is balanced with bright top notes, so it never feels old-fashioned.', 'Perfumeria Concierge', '2026-07-01'::date);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('aurelia-fiori-bianchi', 'Fiori Bianchi', (select id from public.brands where name = 'Aurelia' limit 1), 'women'::product_category, 'women'::gender_t, 'EDP'::concentration, ARRAY['floral','green','fresh'], 'White flowers after the rain. Tuberose, jasmine sambac, and a clean fig-leaf base.', 'Hand-blended in a small atelier outside Florence, Aurelia crafts each bottle in small batches using locally-sourced botanicals.', ARRAY['Italian Bergamot','Green Mandarin','Pear Nectar'], ARRAY['Tuberose','Jasmine Sambac','Orange Blossom'], ARRAY['Fig Leaf','White Cedar','Skin Musk'], 'Moderate'::longevity_t, 'Intimate'::sillage_t, 4.7, 342, true, false, false, false, NULL, '{}', ARRAY['/products/4.jpg','/products/8.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'aurelia-fiori-bianchi' limit 1), '50ml', 125, 14);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'aurelia-fiori-bianchi' limit 1), '100ml', 195, 9);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'aurelia-fiori-bianchi' limit 1), 'Isabella R.', 'I', 5, '2026-06-15'::date, 'A summer garden in a bottle', 'So fresh and clean. I wear it every day in spring and summer. Compliments everywhere.', '{}', true, 67, 1);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('aurelia-velvet-rose', 'Velvet Rose Oud', (select id from public.brands where name = 'Aurelia' limit 1), 'women'::product_category, 'women'::gender_t, 'Parfum'::concentration, ARRAY['floral','oriental','woody'], 'A high-concentration velvet rose draped in oud, saffron, and a dusting of cocoa. For the romantic maximalist.', 'An Aurelia heritage release, reformulated in 2024 with a richer, more intense heart.', ARRAY['Saffron','Pink Pepper','Bulgarian Rose'], ARRAY['Damask Rose','Turkish Rose','Patchouli'], ARRAY['Oud','Cocoa','Sandalwood','Amber'], 'All-day'::longevity_t, 'Strong'::sillage_t, 4.8, 198, false, false, false, false, NULL, '{}', ARRAY['/products/5.jpg','/products/9.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'aurelia-velvet-rose' limit 1), '30ml', 175, 6);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'aurelia-velvet-rose' limit 1), '50ml', 245, 11);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'aurelia-velvet-rose' limit 1), 'Layla A.', 'L', 5, '2026-05-20'::date, 'Heady and addictive', 'One spray is enough. It''s heavy, sensual, and lasts 12+ hours. My favorite winter scent.', '{}', true, 45, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('kintsugi-ceremony', 'Ceremony', (select id from public.brands where name = 'Kintsugi' limit 1), 'unisex'::product_category, 'unisex'::gender_t, 'EDP'::concentration, ARRAY['woody','green','smoky'], 'A meditative blend of hinoki wood, matcha, and white tea smoke. Wabi-sabi in a bottle.', 'Kintsugi is a small-batch Japanese perfumery that finds beauty in imperfection. Each fragrance is hand-numbered.', ARRAY['Yuzu','Matcha','Bergamot'], ARRAY['Hinoki Wood','Bamboo','White Tea'], ARRAY['Vetiver','Hinoki Smoke','Soft Musk'], 'Moderate'::longevity_t, 'Moderate'::sillage_t, 4.9, 267, true, false, true, false, NULL, '{}', ARRAY['/products/6.jpg','/products/0.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'kintsugi-ceremony' limit 1), '50ml', 165, 12);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'kintsugi-ceremony' limit 1), '100ml', 235, 5);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'kintsugi-ceremony' limit 1), 'Maya T.', 'M', 5, '2026-07-08'::date, 'Calming and unique', 'Smells like a Japanese tea ceremony. Subtle, sophisticated, and so different from anything else in my collection.', ARRAY['/products/2.jpg'], true, 78, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('verdant-citrus-no-7', 'Citrus No. 7', (select id from public.brands where name = 'Verdant' limit 1), 'unisex'::product_category, 'unisex'::gender_t, 'EDT'::concentration, ARRAY['citrus','fresh','green'], 'A bright, juicy blend of seven citrus fruits with a clean vetiver base. California sunshine in a spray.', 'Verdant is a clean beauty house from California. Citrus No. 7 is their breakout hit, made with cold-pressed essential oils.', ARRAY['Sicilian Lemon','Pink Grapefruit','Mandarin','Yuzu','Bergamot','Lime','Kumquat'], ARRAY['Neroli','Petitgrain','Green Tea'], ARRAY['Vetiver','Cedarwood','White Musk'], 'Light'::longevity_t, 'Intimate'::sillage_t, 4.6, 612, false, true, false, false, NULL, '{}', ARRAY['/products/7.jpg','/products/1.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'verdant-citrus-no-7' limit 1), '30ml', 58, 22);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'verdant-citrus-no-7' limit 1), '50ml', 88, 30);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'verdant-citrus-no-7' limit 1), '100ml', 145, 18);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'verdant-citrus-no-7' limit 1), 'Theo K.', 'T', 5, '2026-06-29'::date, 'The perfect summer scent', 'Light, fresh, and crowd-pleasing. Doesn''t last forever but that''s fine — reapply and enjoy.', '{}', true, 89, 3);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('kintsugi-iron-tea', 'Iron Tea', (select id from public.brands where name = 'Kintsugi' limit 1), 'unisex'::product_category, 'unisex'::gender_t, 'Parfum'::concentration, ARRAY['woody','leather','smoky'], 'A smoky, tannic blend of lapsang souchong tea, black iron, and worn leather. The most-bookish scent we make.', 'Limited edition, hand-bottled in numbered runs of 500.', ARRAY['Black Pepper','Smoked Plum'], ARRAY['Lapsang Souchong','Tobacco Leaf','Birch Tar'], ARRAY['Leather','Iron','Oud','Vetiver'], 'All-day'::longevity_t, 'Strong'::sillage_t, 4.9, 87, false, false, false, false, NULL, '{}', ARRAY['/products/8.jpg','/products/2.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'kintsugi-iron-tea' limit 1), '30ml', 215, 4);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'kintsugi-iron-tea' limit 1), '50ml', 295, 7);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'kintsugi-iron-tea' limit 1), 'Rashid B.', 'R', 5, '2026-04-12'::date, 'Worth every dollar', 'A true collector''s piece. Smells like an old library, a smoking jacket, and a leather chair. Stunning.', '{}', true, 34, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('kintsugi-paper-lantern', 'Paper Lantern', (select id from public.brands where name = 'Kintsugi' limit 1), 'niche'::product_category, 'unisex'::gender_t, 'Parfum'::concentration, ARRAY['floral','green','woody'], 'A whisper of wisteria, rice paper, and fresh ink. The scent of a paper lantern glowing at dusk.', 'An award-winning niche release, Paper Lantern won the 2025 Art & Olfaction Award in the independent category.', ARRAY['Wisteria','Rice Steam','White Tea'], ARRAY['Magnolia','Iris','Bamboo'], ARRAY['Hinoki Wood','Soft Musk','Vellum'], 'Moderate'::longevity_t, 'Intimate'::sillage_t, 5, 64, false, false, true, false, NULL, '{}', ARRAY['/products/9.jpg','/products/3.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'kintsugi-paper-lantern' limit 1), '30ml', 245, 3);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'kintsugi-paper-lantern' limit 1), '50ml', 345, 5);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'kintsugi-paper-lantern' limit 1), 'Anna K.', 'A', 5, '2026-07-12'::date, 'Pure artistry', 'An olfactory poem. Subtle, fleeting, and haunting. I save it for special evenings.', '{}', true, 41, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('maison-noir-cuir-sacre', 'Cuir Sacré', (select id from public.brands where name = 'Maison Noir' limit 1), 'niche'::product_category, 'unisex'::gender_t, 'Parfum'::concentration, ARRAY['leather','woody','smoky'], 'Sacred leather, frankincense smoke, and aged birch tar. A cathedral of a fragrance.', 'A 2024 release, Cuir Sacré was composed over three years by our master perfumer in Grasse.', ARRAY['Saffron','Cardamom','Black Pepper'], ARRAY['Frankincense','Myrrh','Cistus'], ARRAY['Sacre Leather','Birch Tar','Oud','Vetiver'], 'All-day'::longevity_t, 'Enormous'::sillage_t, 4.9, 142, true, false, false, false, NULL, '{}', ARRAY['/products/0.jpg','/products/5.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'maison-noir-cuir-sacre' limit 1), '30ml', 285, 4);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'maison-noir-cuir-sacre' limit 1), '50ml', 395, 6);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'maison-noir-cuir-sacre' limit 1), 'Viktor P.', 'V', 5, '2026-05-08'::date, 'Masterpiece', 'Powerful, dark, and absolutely unique. I get stopped on the street. Lasts 14+ hours.', '{}', true, 52, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('atelier-oud-royal', 'Royal Oud', (select id from public.brands where name = 'Atelier Oud' limit 1), 'arabic'::product_category, 'unisex'::gender_t, 'Parfum'::concentration, ARRAY['oriental','woody','spicy'], 'Pure Cambodian oud, aged 25 years, layered with royal saffron, rose, and amber. A modern classic of Arabian perfumery.', 'Atelier Oud has been distilling oud in Abu Dhabi since 1998, working with the finest agarwood from Cambodia, India, and Laos.', ARRAY['Saffron','Pink Pepper','Green Cardamom'], ARRAY['Cambodian Oud','Taif Rose','Saffron Absolute'], ARRAY['Royal Amber','Sandalwood','White Musk','Dehn Al Oud'], 'All-day'::longevity_t, 'Enormous'::sillage_t, 4.9, 387, false, true, true, false, NULL, '{}', ARRAY['/categories/0.jpg','/categories/2.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'atelier-oud-royal' limit 1), '12ml', 195, 8);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'atelier-oud-royal' limit 1), '30ml', 395, 5);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'atelier-oud-royal' limit 1), '50ml', 595, 3);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'atelier-oud-royal' limit 1), 'Faisal M.', 'F', 5, '2026-06-25'::date, 'The real deal', 'Authentic Cambodian oud. Not the synthetic stuff you find elsewhere. Worth every riyal.', '{}', true, 91, 0);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'atelier-oud-royal' limit 1), 'Noura A.', 'N', 5, '2026-05-17'::date, 'My special-occasion scent', 'I save it for Eid and weddings. The compliments never stop. Truly exceptional.', '{}', true, 64, 1);
insert into public.product_qa (product_id, user_name, question, answer, answered_by, qa_date) values ((select id from public.products where slug = 'atelier-oud-royal' limit 1), 'Khalid R.', 'Is this pure oud or blended?', 'Royal Oud is a high-concentration parfum with genuine Cambodian oud at the heart, blended with supporting notes. It is not pure distillation (which would be much more expensive and niche).', 'Perfumeria Concierge', '2026-06-20'::date);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('atelier-oud-mukhallat', 'Mukhallat Maliki', (select id from public.brands where name = 'Atelier Oud' limit 1), 'arabic'::product_category, 'unisex'::gender_t, 'Parfum'::concentration, ARRAY['oriental','floral','spicy'], 'A traditional mukhallat blend of oud, rose, amber, and musk. Worn in the Gulf for generations.', 'Our master perfumer''s grandfather made this exact blend in his shop in Deira in 1962. We reformulated it in 2018.', ARRAY['Saffron','Cinnamon','Green Cardamom'], ARRAY['Oud','Taif Rose','Jasmine'], ARRAY['Amber','Musk','Sandalwood','Dehn'], 'All-day'::longevity_t, 'Strong'::sillage_t, 4.8, 256, false, false, false, false, NULL, '{}', ARRAY['/categories/1.jpg','/categories/3.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'atelier-oud-mukhallat' limit 1), '30ml', 145, 12);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'atelier-oud-mukhallat' limit 1), '50ml', 225, 8);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'atelier-oud-mukhallat' limit 1), 'Yasmin H.', 'Y', 5, '2026-04-30'::date, 'Traditional and authentic', 'Takes me back to my grandmother''s house. A true classic.', '{}', true, 38, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('atelier-oud-amber-dawn', 'Amber Dawn', (select id from public.brands where name = 'Atelier Oud' limit 1), 'arabic'::product_category, 'unisex'::gender_t, 'EDP'::concentration, ARRAY['oriental','spicy','gourmand'], 'Warm amber, vanilla, and a whisper of frankincense. The first golden hour after sunrise.', 'A modern interpretation of traditional amber compositions, launched in 2023.', ARRAY['Pink Pepper','Bergamot'], ARRAY['Amber','Frankincense','Cinnamon Bark'], ARRAY['Vanilla','Benzoin','Sandalwood','White Musk'], 'Long-lasting'::longevity_t, 'Moderate'::sillage_t, 4.7, 178, true, false, false, false, NULL, '{}', ARRAY['/categories/2.jpg','/categories/4.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'atelier-oud-amber-dawn' limit 1), '50ml', 115, 18);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'atelier-oud-amber-dawn' limit 1), '100ml', 185, 11);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'atelier-oud-amber-dawn' limit 1), 'Omar B.', 'O', 5, '2026-05-22'::date, 'Warm and comforting', 'Like a hug in a bottle. Perfect for cold weather.', '{}', true, 29, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('discovery-set-classic', 'Classic Discovery Set', (select id from public.brands where name = 'Maison Noir' limit 1), 'gift-sets'::product_category, 'unisex'::gender_t, 'EDP'::concentration, ARRAY['floral','woody','oriental'], 'A curated set of five 10ml travel sprays from our most-loved releases. The perfect way to find your new signature.', 'The Discovery Set is our most popular gift, designed for sampling or for the traveler who won''t compromise.', ARRAY['Mixed'], ARRAY['Mixed'], ARRAY['Mixed'], 'Moderate'::longevity_t, 'Moderate'::sillage_t, 4.8, 1243, false, true, true, false, NULL, '{}', ARRAY['/categories/3.jpg','/categories/5.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'discovery-set-classic' limit 1), '5 x 10ml', 95, 30);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'discovery-set-classic' limit 1), 'Olivia P.', 'O', 5, '2026-07-01'::date, 'Best way to find your signature', 'Tried all five and ended up buying two full bottles. The travel size is perfect for my purse.', ARRAY['/categories/3.jpg'], true, 156, 3);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('his-and-hers-gift-set', 'His & Hers Discovery', (select id from public.brands where name = 'Aurelia' limit 1), 'gift-sets'::product_category, 'unisex'::gender_t, 'EDP'::concentration, ARRAY['floral','woody'], 'Two of our most-loved fragrances in a beautifully boxed gift set. Includes Rosa Velvet (her) and Cedar Smoke (him).', 'Our bestselling gift for couples, available seasonally in limited-edition packaging.', ARRAY['Mixed'], ARRAY['Mixed'], ARRAY['Mixed'], 'Long-lasting'::longevity_t, 'Moderate'::sillage_t, 4.9, 412, false, false, true, false, NULL, '{}', ARRAY['/categories/4.jpg','/categories/6.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'his-and-hers-gift-set' limit 1), '2 x 50ml', 245, 18);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'his-and-hers-gift-set' limit 1), 'James & Sarah', 'J', 5, '2026-02-14'::date, 'Anniversary perfection', 'Bought this for our anniversary and we both love it. The packaging is gorgeous too.', '{}', true, 87, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('luxury-oud-collection', 'Luxury Oud Collection', (select id from public.brands where name = 'Atelier Oud' limit 1), 'gift-sets'::product_category, 'unisex'::gender_t, 'Parfum'::concentration, ARRAY['oriental','woody','spicy'], 'Our most prestigious oud collection: Royal Oud, Mukhallat Maliki, and Amber Dawn in a hand-finished wooden box.', 'The Luxury Oud Collection is presented in a hand-finished walnut box, with a numbered certificate of authenticity.', ARRAY['Mixed'], ARRAY['Mixed'], ARRAY['Mixed'], 'All-day'::longevity_t, 'Strong'::sillage_t, 5, 78, true, false, false, false, NULL, '{}', ARRAY['/categories/5.jpg','/categories/7.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'luxury-oud-collection' limit 1), '3 x 30ml', 695, 6);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'luxury-oud-collection' limit 1), 'Sheikh Mohammed A.', 'S', 5, '2026-03-22'::date, 'An heirloom', 'Bought for my father. The presentation is stunning. The fragrances are even better.', '{}', true, 24, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('maison-noir-vetiver-noir', 'Vetiver Noir', (select id from public.brands where name = 'Maison Noir' limit 1), 'men'::product_category, 'men'::gender_t, 'EDT'::concentration, ARRAY['woody','earthy','aromatic'], 'Haitian vetiver, smoked black tea, and a touch of grapefruit. Sharp, modern, magnetic.', 'Our bestselling everyday men''s scent since 2019.', ARRAY['Grapefruit','Black Pepper','Cardamom'], ARRAY['Smoked Tea','Geranium','Sage'], ARRAY['Haitian Vetiver','Cedarwood','Tonka Bean'], 'Moderate'::longevity_t, 'Moderate'::sillage_t, 4.6, 678, false, true, false, false, NULL, '{}', ARRAY['/products/1.jpg','/products/5.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'maison-noir-vetiver-noir' limit 1), '50ml', 95, 25);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'maison-noir-vetiver-noir' limit 1), '100ml', 145, 18);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'maison-noir-vetiver-noir' limit 1), 'Tom H.', 'T', 5, '2026-06-08'::date, 'Daily driver', 'My go-to for the office. Clean, masculine, never overpowering.', '{}', true, 56, 0);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('verdant-ocean-mist', 'Ocean Mist', (select id from public.brands where name = 'Verdant' limit 1), 'men'::product_category, 'men'::gender_t, 'EDT'::concentration, ARRAY['aquatic','fresh','citrus'], 'Sea salt, driftwood, and white musk. A clean, breezy aquatic.', 'A summer 2024 release inspired by the California coast.', ARRAY['Sea Salt','Bergamot','Cucumber'], ARRAY['Driftwood','Sage','Mint'], ARRAY['White Musk','Ambergris','Cedar'], 'Light'::longevity_t, 'Moderate'::sillage_t, 4.4, 312, false, false, false, false, NULL, '{}', ARRAY['/products/2.jpg','/products/6.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'verdant-ocean-mist' limit 1), '50ml', 75, 22);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'verdant-ocean-mist' limit 1), '100ml', 115, 14);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'verdant-ocean-mist' limit 1), 'Chris M.', 'C', 4, '2026-05-14'::date, 'Fresh and clean', 'Great for summer. Doesn''t last as long as I''d like but it smells great while it''s there.', '{}', true, 22, 1);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('rosa-velvet-noir-rose', 'Noir Rose', (select id from public.brands where name = 'Rosa Velvet' limit 1), 'women'::product_category, 'women'::gender_t, 'EDP'::concentration, ARRAY['floral','gourmand','oriental'], 'A dark, modern rose. Damask rose, black cherry, and a base of patchouli and vanilla.', 'The dark sister to our original Rosa Velvet, launched in 2023.', ARRAY['Black Cherry','Bergamot','Pink Pepper'], ARRAY['Damask Rose','Liqueur','Geranium'], ARRAY['Patchouli','Vanilla','Sandalwood'], 'Long-lasting'::longevity_t, 'Strong'::sillage_t, 4.8, 421, false, false, false, false, NULL, '{}', ARRAY['/products/3.jpg','/products/7.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'rosa-velvet-noir-rose' limit 1), '30ml', 125, 9);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'rosa-velvet-noir-rose' limit 1), '50ml', 185, 13);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'rosa-velvet-noir-rose' limit 1), 'Beatriz S.', 'B', 5, '2026-04-25'::date, 'A modern rose masterpiece', 'Reminds me of Tom Ford''s Lost Cherry but better. Long-lasting, unique, gorgeous.', '{}', true, 73, 1);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('aurelia-vanilla-velvet', 'Vanilla Velvet', (select id from public.brands where name = 'Aurelia' limit 1), 'women'::product_category, 'women'::gender_t, 'EDP'::concentration, ARRAY['gourmand','oriental','floral'], 'Madagascar vanilla, tonka bean, and a heart of jasmine. Warm, sweet, comforting.', 'Our bestselling gourmand release of 2024.', ARRAY['Bergamot','Mandarin'], ARRAY['Jasmine','Heliotrope','Almond'], ARRAY['Madagascar Vanilla','Tonka Bean','Sandalwood','White Musk'], 'Long-lasting'::longevity_t, 'Moderate'::sillage_t, 4.7, 567, false, true, false, false, NULL, '{}', ARRAY['/products/4.jpg','/products/8.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'aurelia-vanilla-velvet' limit 1), '50ml', 115, 20);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'aurelia-vanilla-velvet' limit 1), '100ml', 175, 12);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'aurelia-vanilla-velvet' limit 1), 'Emma J.', 'E', 5, '2026-06-30'::date, 'Cozy and addictive', 'Smells like vanilla cake, in the best possible way. I want to bathe in it.', '{}', true, 91, 2);
insert into public.products (slug, name, brand_id, category, gender, concentration, scent_families, description, brand_story, top_notes, heart_notes, base_notes, longevity, sillage, rating, review_count, is_new, is_bestseller, is_featured, is_on_sale, original_price, tags, images) values ('verdant-fig-leaf', 'Fig Leaf & Tea', (select id from public.brands where name = 'Verdant' limit 1), 'unisex'::product_category, 'unisex'::gender_t, 'EDT'::concentration, ARRAY['green','fresh','woody'], 'Fresh fig leaf, green tea, and a clean cedarwood base. The most ''California'' scent we make.', 'A summer staple, launched in 2022.', ARRAY['Fig Leaf','Lemon','Green Tea'], ARRAY['Fig','Jasmine','Mint'], ARRAY['Cedarwood','White Musk','Sandalwood'], 'Light'::longevity_t, 'Intimate'::sillage_t, 4.5, 289, false, false, false, false, NULL, '{}', ARRAY['/products/5.jpg','/products/9.jpg']);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'verdant-fig-leaf' limit 1), '50ml', 85, 18);
insert into public.product_variants (product_id, size, price, stock) values ((select id from public.products where slug = 'verdant-fig-leaf' limit 1), '100ml', 135, 9);
insert into public.product_reviews (product_id, user_name, avatar, rating, review_date, title, body, photos, verified, helpful, unhelpful) values ((select id from public.products where slug = 'verdant-fig-leaf' limit 1), 'Sara L.', 'S', 5, '2026-07-04'::date, 'A green dream', 'So fresh and clean. I wear it in summer and get compliments daily.', '{}', true, 41, 0);

-- ===== Promo codes =====
insert into public.promo_codes (code, type, value, min_order, description, expires_at) values ('WELCOME10', 'percent', 10, 50, '10% off your first order over $50', '2026-12-31 23:59:59+00');
insert into public.promo_codes (code, type, value, min_order, description, expires_at) values ('SCENT20', 'percent', 20, 150, '20% off orders over $150', '2026-12-31 23:59:59+00');
insert into public.promo_codes (code, type, value, min_order, description, expires_at) values ('GIFT15', 'fixed', 15, 75, '$15 off gift sets over $75', '2026-12-31 23:59:59+00');
insert into public.promo_codes (code, type, value, min_order, description, expires_at) values ('OUD25', 'percent', 25, 200, '25% off oud collection over $200', '2026-12-31 23:59:59+00');

commit;

-- 8 brands, 22 products seeded.